name: app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15
  http: ^1.2.1 # Para fazer requisições HTTP
  flutter_secure_storage: ^9.0.0 # Para armazenar o token de forma segura

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl: ^0.18.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/


